### ISSUE TITLE
auto_xhr - beacon missing

### ISSUE THREAD

**Issue by AlphaCodeXB** [SOASTA/boomerang#83] opened 2016-03-29 12:44 UTC
Hi everyone,
I'm using boomerang for my traditional website with xhr calls.
I use the plugins rt, navtiming, restiming and auto_xhr.
Before I used the plugin auto_xhr, every page was measured fine.
Since including auto_xhr often the onload-beacons of the pages are missing. 
Why are these beacons missing?
Thanks in advance.

**Comment by nicjansma** [comment] 2016-04-04 13:28
When using a debug build of boomerang, you should see `console.log` messages from boomerang throughout its lifecycle.  Can you share them?  You may see something like this that will tell the culprit:

```
Plugin XYZ is not complete, deferring beacon send
```

**Comment by andreas-marschke** [comment] 2016-04-25 13:57
@AlphaCodeXB Hey an news on this issue?

**Comment by AlphaCodeXB** [comment] 2016-04-26 07:59
I'm sorry but there are no further news. It's still the same problem. I think the problem is that the xhrsrequests are running during the pageload but I'm not sure. First I have tested that the XMLHttpRequest function recognizes all xhrs. While executing the rest of the code it seems like execution stops when a new click-event recognizes a new xhr. If I reduce the timeout value a bit sometimes execution is so well und sometimes not. It's a 50:50 chance. I think it depends on the receiving of the xhr response.

**Comment by andreas-marschke** [comment] 2016-04-26 09:07
Can you boil down the problem into a (semi-) reproducible HTML snippet?

Maybe include your configuration in `plugins.json` so we can compare with latest etc.
It would be great to see if we can reproduce it on our end as well.

**Comment by AlphaCodeXB** [comment] 2016-04-27 14:37
Hey,
I tried to make a HTML snippet, you asked for. It's uploaded in dropbox.
Here is the link:
https://www.dropbox.com/sh/jy57ts75cdo74nv/AADBa1Z3-UxRTrn4Mne92v5Ca?dl=0
Hope it helps to understand my problem.
Thanks in advance.

**Comment by AlphaCodeXB** [comment] 2016-05-01 13:13
By the way I wrote some thoughts about the snippet in index.html and updated the changed boomerang.js. There were still problems with the last one. I keep on testing about the problem I have.

**Comment by nicjansma** [comment] 2016-05-02 13:46
Hi @AlphaCodeXB I'm glad you got it to work for your site with `boomerang_changes.js`.

It looks like the issue with the page load beacon not being sent is due to an issue related to "beacon merging", where multiple beacons are being sent at around the same time, and they end up as a single beacon.

We have a fix for this that we'll be backporting here soon.

**Comment by AlphaCodeXB** [comment] 2016-05-03 13:59
Hi nicjansma, thank you for your fast answer and evaluation. 
I completely agree with you. The problem is caused by too many beacons sent at the same time.

How long will it take to backport the fix?
Is it a big change compared to the current version or can I get the fix earlier to test it?
Thank you very much for your effort.

**Comment by nicjansma** [comment] 2016-06-27 01:29
Fixes are available in https://github.com/SOASTA/boomerang/pull/98

**Closed by nicjansma** 2016-06-27 01:29 UTC

**Comment by AlphaCodeXB** [comment] 2016-06-28 09:23
Here is the link to the simple code snippet again.
You'll see in the developer console there are 10 xmlhttprequests sent by the page to the "controller" but only for a few of them are beacons ready to sent with measuremets. 
https://www.dropbox.com/sh/1o55eikpje7q9ib/AAACMV1vMxUJ21u-jGSoROGya?dl=0

**Comment by nicjansma** [comment] 2016-07-07 23:54
@AlphaCodeXB look into `alwaysSendXhr` as an option for `AutoXHR`.  It might do what you want?

The option instructs BOOMR to always send a beacon for every XHR, even if it happens during a SPA nav or before the page load.

**Comment by AlphaCodeXB** [comment] 2016-08-10 16:23
Hi nicjansma,
I looked at the variable alwaysSendXhr that you told me. 
Am I right that boomerang will send the times for the plain xhr then?
In my case, there is always a change in HTML elements following the xhr.
So I'm sorry but l think it's no solution for me.
Is there another solution that you know?
Thank you very much for your efforts and help.
